### PR TITLE
Have /jenkins-is-the-way/ instead of /user-story/ in the URLs

### PR DESCRIPTION
**Pull request by nouralmulhem**
this PR is addressing [issue#11](https://github.com/jenkins-infra/stories/issues/11)

### **Before:**
image

### **Example of After:**
image

### CODE REVIEW

**Comment by halkeye** [comment]
Just FYI. This will break every link to the site

**Comment by nouralmulhem** [comment]
okay, got your point so this need to be updated in jenkines.io for example as well

**Comment by nouralmulhem** [comment]
how to collect the number of repositories need to be updated ?

**Comment by halkeye** [comment]
I'm general if a URL exists in the wild it should stay working in the wild.  If you change URLs then redirects should get added to do migration

**Comment by MarkEWaite** [comment]
I don't think the benefit from this change is worth the effort to implement it.  Redirects for the existing pages seem like a lot of work for relatively little gain.

**Comment by nouralmulhem** [comment]
@MarkEWaite i agree, after reviewing @halkeye comment also I feel I'm not aware of all the places will be affected with this change
thank your for the feedback

**Pull request closed without merging**
