### PR TITLE
Replace manifest's icon from one from jenkins.io

### PR DESCRIPTION
**Pull request by NotMyFault**

### CODE REVIEW

**Comment by halkeye** [comment]
I'm not sure what this is fixing. The manifest has an icon, and i think the favicon from jenkins.io is small, and manifest wants like 512

image

**Comment by NotMyFault** [comment]
> I'm not sure what this is fixing.

This PR exchanges the gatsby icon with the Jenkins one, to prevent putting the gatsby logo in place, which currently is distributed as https://stories.jenkins.io/favicon-32x32.png?v=53aa06cf17e4239d0dba6ffd09854e02

**Comment by halkeye** [comment]
This is so weird. I clearly (as screenshotted) see the jenkins icon, but https://realfavicongenerator.net/favicon_checker?protocol=https&site=stories.jenkins.io does show the gatsby icon for the app icon manifest.

**Comment by halkeye** [comment]
```
curl -qs 'https://stories.jenkins.io/' | tr '<' '\n' | grep manifest
link data-react-helmet="true" href="/site.webmanifest" rel="manifest"/>
link rel="manifest" href="/manifest.webmanifest" crossorigin="anonymous"/>
```

Looks like we have two manifest, one from the site layout plugin, one from the manifest plugin

**Comment by halkeye** [comment]
So I think the proper fix is to 1) remove that gatsby plugin 2) update [gatsby-plugin-jenkins-layout](https://github.com/jenkins-infra/gatsby-plugin-jenkins-layout/blob/main/makeLayout.js#L208-L220) to take in name and shortname.

I can handle #2 as soon as i finish breakfast and my electronics work.

**Comment by NotMyFault** [comment]
> So I think the proper fix is to 1) remove that gatsby plugin

Done 1), I also removed the obsolete gatsby png.

**Pull request merged**
