### PR TITLE
feat: add link to story image and title in the "/all" listing and format dates

### PR DESCRIPTION
**Pull request by lemeurherve**
<details>
<summary>Before</summary>

image

</details>

<details>
<summary>After</summary>

image

</details>

### CODE REVIEW

**Comment by lemeurherve** [comment]
Fix of the infra.ci.jenkins.io pipeline [here](https://github.com/jenkins-infra/stories/pull/7), no idea why the netlify build failed, "it works on my machine" ^^

**Comment by halkeye** [comment]
> ###  Deploy Preview for _jenkins-is-the-way_ failed.
> Name	Link
>  Latest commit	[6bdef2e](https://github.com/jenkins-infra/stories/commit/6bdef2e51efc4dd505725a347e639c63b890dd22)
>  Latest deploy log	https://app.netlify.com/sites/jenkins-is-the-way/deploys/62a90c50202a06000983d097

uh... why is netlify trying to build the PR. we shouldn't be using their build system at all. Lemme fix.

**Comment by halkeye** [comment]
Change looks good. I can't look at infra.ci till i'm on the other computer though.

**Comment by halkeye** [comment]
~I think it was failing due to netlify previews being enabled~ or not - https://deploy-preview-6--jenkins-jenkins-is-the-way.netlify.app/ is 404ing

**Review by halkeye — APPROVED** [review]
lgtm. I think @MarkEWaite and @alyssat should probably weigh in.

**Pull request merged**
