### PR TITLE
Create User Story “customers-digital-transformation/index”

### PR DESCRIPTION
**Pull request by kmartens27**
This pull request it to create a new story for Alauda. There were issues submitting it from their end so I have compiled the content shared into a pull request for them.

Since I do not have some of the information readily available, this PR will allow us to collaborate and fill in any missing information.

@yuzp1996 I will be adding a few lines for information to be added and be sure to share what those are once I've submitted the changes to this PR. Also, if there is any information that needs to be updated, please share those changes/feedback here so that we can get everything aligned.

### CODE REVIEW

**Comment by yuzp1996** [comment]
> Hi @yuzp1996, I have added the `programming_langauges`, `platforms`, and `build_tools` areas but would need your assistance in filling those out. Additionally, if there are any other version control systems that should be added, please be sure to add them accordingly.
> 
> I also added an industry, but if that is incorrect please update it to what it should be.
> 
> Please let me know what other changes need to be made, and I can adjust things as needed.
> 
> Thank you very much for your interest in sharing and collaborating with the project!

Thank you soooooo much! I'll definitely check it and give feedback here as soon as I can! 😊

**Comment by yuzp1996** [comment]
> > Hi @yuzp1996, I have added the `programming_langauges`, `platforms`, and `build_tools` areas but would need your assistance in filling those out. Additionally, if there are any other version control systems that should be added, please be sure to add them accordingly.
> > I also added an industry, but if that is incorrect please update it to what it should be.
> > Please let me know what other changes need to be made, and I can adjust things as needed.
> > Thank you very much for your interest in sharing and collaborating with the project!
> 
> Thank you soooooo much! I'll definitely check it and give feedback here as soon as I can! 😊
 
I adjust `submitted_by` `programming_langauges` `platforms` `version_control_systems` `build_tools` as below!

Thanks for your efforts! 🌹

```
title: Facilitating Customers' Digital Transformation Based on Jenkins
post_name: customers-digital-transformation
submitted_by: Zhipeng Yu
date: 2024-11-21T10:28.846-05:00
tag_line: "Alauda: The AI-Ready Cloud Native Solution"
image: alauda.png
metadata:
  organization: Alauda, [alauda.io](https://www.alauda.io/)
  industries:
    - DevOps
  programming_langauges:
    - Java
  platforms:
    - Linux
    - Docker
    - Kubernetes
  version_control_systems:
    - GitHub
    - Gitlab
  build_tools:
    - Make
    - Gradle
    - Maven
  community_supports:
    - Yes
```

**Review by gounthar — APPROVED** [review]
Looks good to me, thanks! 👍

**Comment by yuzp1996** [comment]
> Hi @yuzp1996, would you happen to have a non-transparent version of the alauda logo? When reviewing the deploy preview link on my browser (dark mode), the logo is barely visible except for the blue parts: Screenshot 2024-11-25 at 10 59 31 AM
> 
> Everything else looks good, but if you would also be able to review the deploy site and provide any feedback, that would be great. https://deploy-preview-73--jenkins-is-the-way.netlify.app/user-story/customers-digital-transformation

Thanks here is the non-transparent version of the alauda logo

alauda

**Review by MarkEWaite — APPROVED** [review]

**Pull request merged**
